#!/usr/bin/env bash

sed -i 's/"version": ".*"/"version": "'$1'"/' package.json
find \
| grep \.csproj$ \
| xargs sed -i 's/<PackageVersion>.*<\/PackageVersion>/<PackageVersion>'$1'<\/PackageVersion>/'

git commit -am "Release $1"
git push

git tag $1
git push --tags