name: CI
on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  Mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Test Mac scanner
        run: dotnet test Mac.Tests -p:RuntimeIdentifier= -p:PublishSingleFile=false

  Server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install dependencies
        run: dotnet restore -p:RuntimeIdentifier= -p:PublishSingleFile=false

      - name: Build
        run: dotnet build --no-restore -p:RuntimeIdentifier= -p:PublishSingleFile=false

      - name: Test
        run: dotnet test --no-build --verbosity normal -p:RuntimeIdentifier= -p:PublishSingleFile=false

  App:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Node.JS
        uses: actions/setup-node@v6
        with:
          node-version: 26

      - name: Install dependencies
        run: yarn install
        env:
          YARN_ENABLE_SCRIPTS: false

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
