name: CI
on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  Server:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - project: Core.Tests
            runner: ubuntu-latest
            options: -p:RuntimeIdentifier=
          - project: Linux.Tests
            runner: ubuntu-latest
            options: -p:RuntimeIdentifier=
          - project: Windows.Tests
            runner: ubuntu-latest
            options: -p:RuntimeIdentifier=
          - project: Mac.Tests
            runner: xcode-27
            options: ''

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install macOS workload
        if: matrix.project == 'Mac.Tests'
        run: |
          dotnet workload install macos --version 10.0.401.1
          dotnet workload restore Mac.Tests/Mac.Tests.csproj

      - name: Install dependencies
        run: dotnet restore ${{ matrix.project }} ${{ matrix.options }}

      - name: Build
        run: dotnet build ${{ matrix.project }} ${{ matrix.options }} --no-restore

      - name: Test
        run: dotnet test ${{ matrix.project }} ${{ matrix.options }} --no-build --verbosity normal

  App:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Node.JS
        uses: actions/setup-node@v6
        with:
          node-version: 26

      - name: Install dependencies
        run: yarn install
        env:
          YARN_ENABLE_SCRIPTS: false

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
