name: Release
on:
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  Publish:
    runs-on: ${{ matrix.os == 'osx' && 'xcode-27' || 'ubuntu-latest' }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [linux, osx, win]
        arch: [x64, arm64]
        include:
          - dir: Linux
            os: linux
          - dir: Mac
            os: osx
          - dir: Windows
            os: win

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          ref: ${{ github.ref }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install macOS workload
        if: matrix.os == 'osx'
        run: |
          dotnet workload install macos --version 10.0.401.1
          dotnet workload restore Mac.Tests/Mac.Tests.csproj

      - name: Setup Node.JS
        uses: actions/setup-node@v6
        with:
          node-version: 26

      - name: Install zip packager
        if: runner.os == 'Linux'
        run: sudo apt install zip

      - name: Run server tests
        run: |
          dotnet test Core.Tests -p:RuntimeIdentifier=
          if [[ '${{ matrix.os }}' == 'osx' ]]; then
            dotnet test Mac.Tests
          else
            dotnet test ${{ matrix.dir }}.Tests -p:RuntimeIdentifier=
          fi

      - name: Install app dependencies
        run: yarn install
        env:
          YARN_ENABLE_SCRIPTS: false

      - name: Run app tests
        run: yarn test

      - name: Build app
        run: yarn build

      - name: Publish ${{ matrix.dir }} ${{ matrix.arch }} release
        run: |
          dotnet publish ${{ matrix.dir }} --sc -c Release -r ${{ matrix.os }}-${{ matrix.arch }} -o publish/${{ matrix.os }}-${{ matrix.arch }}
          if [[ '${{ matrix.os }}' == 'osx' ]]; then
            cp -R Mac/bin/Release/net10.0-macos27.0/osx-${{ matrix.arch }}/WiFiSurveyor.app publish/osx-${{ matrix.arch }}/
          fi

      - name: Package ${{ matrix.dir }} ${{ matrix.arch }} release
        working-directory: publish/${{ matrix.os }}-${{ matrix.arch }}
        run: |
          paths=(*)
          if [[ '${{ matrix.os }}' == 'osx' ]]; then
            paths=(WiFiSurveyor.app)
          fi
          zip -9 -r ../WiFiSurveyor-${GITHUB_REF_NAME}-${{ matrix.dir }}-${{ matrix.arch }}.zip "${paths[@]}"

      - name: Upload packaged release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            publish/*.zip
